import { darkColor, lightColor } from './colors'

const base = {
  fontFamilyBase: "'Inter', -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Arial, sans-serif",
  fontFamilyMonospace: "'IBM Plex Mono', Menlo, monospace",
  fontFamilyHeading: "'Merriweather', -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Arial, sans-serif",
  borderRadius: '4px',
  contentWidth: '1060px',
  contentWidthSmall: '560px',
  contentWidthMedium: '700px',
  navbarHeightLarge: '80px',
  navbarHeightSmall: '60px',

  gray0: '250, 250, 250',
  gray05: '246, 246, 246',
  gray1: '238, 238, 238',
  gray2: '230, 230, 230',
  gray3: '221, 221, 221',
  gray4: '187, 187, 187',
  gray5: '153, 153, 153',
  gray6: '102, 102, 102',
  gray65: '85, 85, 85',
  gray7: '44, 44, 44',
  gray8: '36, 36, 36',
  gray9: '31, 31, 31',
  gray10: '20, 20, 20',
}

export const light = {
  ...base,
  ...lightColor,

  pageBackgroundColor: 'white',
  cardBackgroundColor: `rgb(${base.gray05})`,
  inlineCodeBackgroundColor: 'rgba(0, 0, 0, 0.05)',
  cardShadow: 'rgba(0,0,0,0.12)',

  navbarBackgroundColor: `rgba(0,0,0,0)`,
  navbarBorder: `rgb(${base.gray2})`,
  navbarColor: `rgb(${base.gray8})`,
  navbarColorHover: `rgb(${base.gray9})`,

  fontColorBase: `rgb(${base.gray7})`,
  fontColorMuted: `rgb(${base.gray6})`,
  fontColorBright: `rgb(${base.gray9})`,
  fontColorHeading: `rgb(${base.gray9})`,

  borderColor: `rgb(${base.gray3})`,
  borderColorHover: `rgb(${base.gray6})`,
  linkHoverColor: `rgb(${base.gray2})`,
  themeButtonBackground: `rgb(255,255,255)`,
  themeButtonBackgroundHover: `rgb(${base.gray1})`,

  codeFontColor: '#232529',
  codeBackgroundColor: `rgb(${base.gray05})`,
  terminalBackgroundColor: 'white',
  terminalBar: 'webkit-linear-gradient(top, #ebebeb, #d5d5d5)',
  terminalAccent: 'white',
  string: '#3b9039',
  variable: '#383a41',
  property: '#565656',
  number: '#da7430',
  operator: '#a87200',
  punctuation: '#5c6d74',
  comment: '#869496',
  function: '#0174a5',
  keyword: '#111',
  attribute: '#a87200',
  class: '#a346a0',
  tag: '#365ccd',
  error: '#b0292c',
}

export const dark = {
  ...base,
  ...darkColor,

  pageBackgroundColor: `rgb(${base.gray10})`,
  cardBackgroundColor: `rgb(${base.gray8})`,
  inlineCodeBackgroundColor: `rgba(${base.gray8},.9)`,
  cardShadow: `rgba(${base.gray8},0.3)`,

  navbarBackgroundColor: `rgba(0,0,0,0)`,
  navbarBorder: `rgb(${base.gray7})`,
  navbarColor: `rgb(${base.gray4})`,
  navbarColorHover: 'white',

  fontColorBase: `rgb(${base.gray2})`,
  fontColorMuted: `rgb(${base.gray4})`,
  fontColorBright: 'white',
  fontColorHeading: 'white',

  borderColor: `rgb(${base.gray7})`,
  borderColorHover: `rgb(${base.gray6})`,
  linkHoverColor: `rgb(${base.gray2})`,
  themeButtonBackground: `rgb(${base.gray10})`,
  themeButtonBackgroundHover: `rgb(${base.gray9})`,

  codeFontColor: '#b3b9c5',
  codeBackgroundColor: `rgb(${base.gray8})`,
  terminalBackgroundColor: '#111',
  terminalBar: 'webkit-linear-gradient(top, #444, #222)',
  terminalAccent: `rgb(${base.gray6})`,
  string: '#92d192',
  variable: '#f2777a',
  property: '#b3b9c5',
  number: '#fca369',
  operator: '#ac8d58',
  punctuation: '#c7cdd7',
  comment: '#777c85',
  function: '#76d4d6',
  keyword: '#ffeea6',
  attribute: '#ffd479',
  class: '#e1a6f2',
  tag: '#6ab0f3',
  error: '#b0292c',
}
