import { DefaultTheme } from 'styled-components'

const base = {
  fontFamilyBase: "'Inter', -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Arial, sans-serif",
  fontFamilyMonospace: "'IBM Plex Mono', Menlo, monospace",
  fontFamilyHeading: "'Merriweather', -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Arial, sans-serif",
  borderRadius: '4px',
  contentWidth: '1060px',
  contentWidthSmall: '560px',
  contentWidthMedium: '700px',
  navbarHeightLarge: '80px',
  navbarHeightSmall: '60px',
  indigoLight: 'var(--indigo-light)',
}

export const light: DefaultTheme = {
  ...base,
  backgroundColor: 'white',
  cardBackgroundColor: 'var(--gray-0)',
  inlineCodeBackgroundColor: 'rgba(0, 0, 0, 0.05)',
  fileBackground: '#e9ecef',
  blockquoteBackground: 'rgba(120, 120, 255, 0.15)',
  blockquoteBoxShadow: 'rgba(120, 120, 255, 0.1)',
  year: 'var(--green)',
  star: 'var(--yellow)',
  fontColorBase: 'var(--gray-7)',
  fontColorMuted: 'var(--gray-6)',
  fontColorHeading: 'var(--gray-8)',
  fontColorBright: 'var(--gray-9)',
  fontColorHeroHeading: 'var(--gray-0)',
  borderColor: 'var(--gray-3)',
  borderColorHover: 'var(--gray-6)',
  link: 'var(--indigo)',
  linkHoverColor: 'var(--indigo-muted)',
  navbar: 'rgba(214, 221, 229, 0.3)',
  navbarBorder: 'var(--gray-2)',
  navbarColor: 'var(--gray-8)',
  navbarColorHover: 'var(--gray-9)',
  themeButtonBackground: 'var(--gray-2)',
  themeButtonBackgroundHover: 'var(--gray-3)',
  themeButtonBorder: 'var(--gray-4)',
  themeButtonBorderHover: 'var(--gray-5)',
  themeButtonColor: 'var(--gray-7)',
  themeButtonColorHover: 'var(--gray-9)',
  marker: '#da66b7',
  postTimeColor: 'var(--gray-6)',
  cardTimeColor: 'var(--gray-6)',
  projectTimeColor: 'var(--font-color-muted)',
  highlightColor: 'var(--green)',
  selectionColor: '#7c82f7',

  cardShadow: 'rgba(0,0,0,0.09)',

  codeFontColor: '#232529',
  codeBackgroundColor: 'var(--gray-0)',
  terminalBackgroundColor: 'white',
  terminalBar: 'webkit-linear-gradient(top, #ebebeb, #d5d5d5)',
  terminalColor: 'var(--code-font-color)',
  terminalAccent: 'white',
  terminalBorder: '#cecbce',
  string: '#3b9039',
  variable: '#383a41',
  property: '#565656',
  number: '#da7430',
  operator: '#a87200',
  punctuation: '#5c6d74',
  comment: '#869496',
  function: '#0174a5',
  keyword: '#111',
  attribute: '#a87200',
  class: '#a346a0',
  tag: '#365ccd',
  error: '#b0292c',
}

export const dark: DefaultTheme = {
  ...base,
  backgroundColor: 'var(--gray-8)',
  cardBackgroundColor: 'var(--gray-9)',
  inlineCodeBackgroundColor: 'rgba(0, 0, 0, 0.1)',
  fileBackground: 'rgba(0, 0, 0, 0.2)',
  blockquoteBackground: 'rgba(120, 120, 255, 0.2)',
  blockquoteBoxShadow: 'rgba(120, 120, 255, 0.1)',
  star: 'var(--rainbow-5)',
  year: 'var(--rainbow-4)',
  fontColorHeading: 'white',
  fontColorHeading3: 'var(--gray-1)',
  fontColorBase: 'var(--gray-2)',
  fontColorMuted: 'var(--gray-4)',
  fontColorBright: 'white',
  borderColor: 'var(--gray-7)',
  borderColorHover: 'var(--gray-6)',
  link: '#a4a9ff',
  linkHoverColor: '#222',
  navbar: 'rgba(0, 0, 0, 0.3)',
  navbarBorder: 'var(--gray-7)',
  navbarColor: 'var(--gray-4)',
  navbarColorHover: 'white',
  themeButtonBackground: 'var(--gray-8)',
  themeButtonBackgroundHover: 'var(--gray-7)',
  themeButtonBorder: 'var(--gray-7)',
  themeButtonBorderHover: 'var(--gray-6)',
  themeButtonColor: 'var(--gray-0)',
  themeButtonColorHover: 'white',
  marker: '#e77cc7',
  postTimeColor: 'var(--rainbow-4)',
  cardTimeColor: 'var(--rainbow-1)',
  projectTimeColor: 'var(--star)',
  highlightColor: 'var(--rainbow-4)',
  selectionColor: '#646cff',

  cardShadow: 'rgba(0,0,0,0.2)',

  codeFontColor: '#b3b9c5',
  codeBackgroundColor: 'var(--gray-9)',
  terminalBackgroundColor: '#111',
  terminalColor: 'var(--rainbow-4)',
  terminalBar: 'webkit-linear-gradient(top, #444, #222)',
  terminalBorder: 'var(--border-color)',
  terminalAccent: 'var(--gray-6)',
  string: '#92d192',
  variable: '#f2777a',
  property: '#b3b9c5',
  number: '#fca369',
  operator: '#ac8d58',
  punctuation: '#c7cdd7',
  comment: '#777c85',
  function: '#76d4d6',
  keyword: '#ffeea6',
  attribute: '#ffd479',
  class: '#e1a6f2',
  tag: '#6ab0f3',
  error: '#b0292c',
}
